import { BadRequestException, NotFoundException } from '@nestjs/common';
import { OrderType, Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { branchDepartmentScopeWhere, RequestUser } from '../auth/data-scope';

const supplierSelect = {
  id: true,
  supplierCode: true,
  name: true,
} satisfies Prisma.SupplierSelect;

const serviceSelect = {
  id: true,
  sku: true,
  serviceName: true,
} satisfies Prisma.SupplierServiceSelect;

export async function getHotelBookingOrderDocument(prisma: PrismaService, type: OrderType, id: string, user?: RequestUser) {
  if (type !== OrderType.HOTEL_BOOKING) throw new BadRequestException('Chứng từ hiện chỉ hỗ trợ Booking phòng khách sạn');

  const order = await prisma.order.findFirst({
    where: branchDepartmentScopeWhere<Prisma.OrderWhereInput>({ id, type: OrderType.HOTEL_BOOKING, deletedAt: null }, user),
    select: {
      id: true,
      type: true,
      systemCode: true,
      tourCode: true,
      holdCode: true,
      name: true,
      route: true,
      marketGroup: true,
      bookingDate: true,
      paymentDate: true,
      startDate: true,
      endDate: true,
      status: true,
      paymentStatus: true,
      costStatus: true,
      currency: true,
      exchangeRate: true,
      createdBy: true,
      createdDate: true,
      branch: true,
      department: true,
      customerId: true,
      customerName: true,
      customerType: true,
      customerPhone: true,
      customerEmail: true,
      customerAddress: true,
      agencyName: true,
      collaborator: true,
      operatorOwner: true,
      adultQty: true,
      childQty: true,
      infantQty: true,
      quantity: true,
      roomClass: true,
      servicePackage: true,
      receiveDeadline: true,
      closeDeadline: true,
      totalRevenue: true,
      paidAmount: true,
      remainingRevenue: true,
      totalCost: true,
      paidCost: true,
      remainingCost: true,
      profit: true,
      commission: true,
      commissionStatus: true,
      note: true,
      surveyDescription: true,
      salesItems: {
        select: {
          id: true,
          serviceType: true,
          description: true,
          quantity: true,
          serviceCount: true,
          unitPrice: true,
          vat: true,
          amount: true,
          note: true,
          supplier: { select: supplierSelect },
          service: { select: serviceSelect },
        },
        orderBy: { sortOrder: 'asc' },
      },
      operationItems: {
        select: {
          id: true,
          serviceType: true,
          bookingCode: true,
          serviceDate: true,
          quantity: true,
          netPrice: true,
          vat: true,
          amount: true,
          status: true,
          note: true,
          supplier: { select: supplierSelect },
          service: { select: serviceSelect },
        },
        orderBy: { sortOrder: 'asc' },
      },
      members: {
        select: {
          id: true,
          fullName: true,
          gender: true,
          birthday: true,
          phone: true,
          email: true,
          identityNumber: true,
          issuedDate: true,
          nationality: true,
          passengerType: true,
          note: true,
        },
        orderBy: { sortOrder: 'asc' },
      },
      terms: {
        select: { id: true, language: true, terms: true, notes: true },
        orderBy: { language: 'asc' },
      },
      surveyQuestions: {
        select: { id: true, question: true, note: true },
        orderBy: { sortOrder: 'asc' },
      },
    } satisfies Prisma.OrderSelect,
  });

  if (!order) throw new NotFoundException('Không tìm thấy Booking phòng khách sạn');

  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    title: 'PHIẾU BOOKING PHÒNG KHÁCH SẠN',
    order: {
      id: order.id,
      type: order.type,
      systemCode: order.systemCode,
      tourCode: order.tourCode,
      holdCode: order.holdCode,
      name: order.name,
      route: order.route,
      marketGroup: order.marketGroup,
      bookingDate: iso(order.bookingDate),
      paymentDate: iso(order.paymentDate),
      startDate: iso(order.startDate),
      endDate: iso(order.endDate),
      status: order.status,
      paymentStatus: order.paymentStatus,
      costStatus: order.costStatus,
      currency: order.currency,
      exchangeRate: number(order.exchangeRate),
      createdBy: order.createdBy,
      createdDate: iso(order.createdDate),
      branch: order.branch,
      department: order.department,
      agencyName: order.agencyName,
      collaborator: order.collaborator,
      operatorOwner: order.operatorOwner,
      adultQty: order.adultQty,
      childQty: order.childQty,
      infantQty: order.infantQty,
      quantity: order.quantity,
      roomClass: order.roomClass,
      servicePackage: order.servicePackage,
      receiveDeadline: iso(order.receiveDeadline),
      closeDeadline: iso(order.closeDeadline),
      note: order.note,
    },
    customer: {
      id: order.customerId,
      name: order.customerName,
      type: order.customerType,
      phone: order.customerPhone,
      email: order.customerEmail,
      address: order.customerAddress,
    },
    totals: {
      totalRevenue: number(order.totalRevenue),
      paidAmount: number(order.paidAmount),
      remainingRevenue: number(order.remainingRevenue),
      totalCost: number(order.totalCost),
      paidCost: number(order.paidCost),
      remainingCost: number(order.remainingCost),
      profit: number(order.profit),
      commission: number(order.commission),
      commissionStatus: order.commissionStatus,
    },
    salesItems: order.salesItems.map((row) => ({
      id: row.id,
      serviceType: row.serviceType,
      description: row.description,
      quantity: number(row.quantity),
      serviceCount: number(row.serviceCount),
      unitPrice: number(row.unitPrice),
      vat: number(row.vat),
      amount: number(row.amount),
      note: row.note,
      supplier: row.supplier,
      service: row.service,
    })),
    operationItems: order.operationItems.map((row) => ({
      id: row.id,
      serviceType: row.serviceType,
      bookingCode: row.bookingCode,
      serviceDate: iso(row.serviceDate),
      quantity: number(row.quantity),
      netPrice: number(row.netPrice),
      vat: number(row.vat),
      amount: number(row.amount),
      status: row.status,
      note: row.note,
      supplier: row.supplier,
      service: row.service,
    })),
    members: order.members.map((row) => ({
      id: row.id,
      fullName: row.fullName,
      gender: row.gender,
      birthday: iso(row.birthday),
      phone: row.phone,
      email: row.email,
      identityNumber: row.identityNumber,
      issuedDate: iso(row.issuedDate),
      nationality: row.nationality,
      passengerType: row.passengerType,
      note: row.note,
    })),
    terms: order.terms,
    survey: {
      description: order.surveyDescription,
      questions: order.surveyQuestions,
    },
    signatures: [
      { label: 'Khách hàng', name: order.customerName },
      { label: 'Nhân viên phụ trách', name: order.createdBy },
      { label: 'Điều hành', name: order.operatorOwner },
    ],
  };
}

function number(value: unknown) {
  const normalized = Number(value);
  return Number.isFinite(normalized) ? normalized : 0;
}

function iso(value?: Date | null) {
  return value ? value.toISOString() : null;
}
