INSERT INTO "Role" ("id", "code", "name", "description", "isSystem", "status", "updatedAt")
VALUES
  ('role_super_admin', 'super_admin', 'Super Admin', 'Full SmartTour administration access', true, 'ACTIVE', NOW()),
  ('role_accounting', 'accounting', 'Ke toan', 'Finance and accounting workflows', true, 'ACTIVE', NOW()),
  ('role_operation', 'operation', 'Dieu hanh', 'Tour operation workflows', true, 'ACTIVE', NOW()),
  ('role_sales', 'sales', 'Kinh doanh', 'Sales, CRM, quotation, and order workflows', true, 'ACTIVE', NOW())
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "isSystem" = EXCLUDED."isSystem",
  "status" = EXCLUDED."status",
  "updatedAt" = NOW();

WITH role_permissions(code, permission) AS (
  VALUES
    ('super_admin', '*'),
    ('super_admin', 'auth.user.manage'),
    ('super_admin', 'auth.role.manage'),
    ('super_admin', 'booking.view'),
    ('super_admin', 'booking.manage'),
    ('super_admin', 'tour.view'),
    ('super_admin', 'tour.manage'),
    ('super_admin', 'guide.view'),
    ('super_admin', 'guide.manage'),
    ('super_admin', 'supplier.view'),
    ('super_admin', 'supplier.manage'),
    ('super_admin', 'order.view'),
    ('super_admin', 'order.manage'),
    ('super_admin', 'quote.view'),
    ('super_admin', 'quote.manage'),
    ('super_admin', 'quotation.view'),
    ('super_admin', 'quotation.manage'),
    ('super_admin', 'customer.view'),
    ('super_admin', 'customer.manage'),
    ('super_admin', 'commission.view'),
    ('super_admin', 'commission.manage'),
    ('super_admin', 'commission.export'),
    ('super_admin', 'commission.approve'),
    ('super_admin', 'report.view'),
    ('super_admin', 'report.export'),
    ('super_admin', 'finance.receipt.view'),
    ('super_admin', 'finance.receipt.create'),
    ('super_admin', 'finance.receipt.update'),
    ('super_admin', 'finance.receipt.delete'),
    ('super_admin', 'finance.receipt.approve'),
    ('super_admin', 'finance.receipt.import'),
    ('super_admin', 'finance.receipt.export'),
    ('super_admin', 'finance.payment.view'),
    ('super_admin', 'finance.payment.create'),
    ('super_admin', 'finance.payment.update'),
    ('super_admin', 'finance.payment.delete'),
    ('super_admin', 'finance.payment.approve'),
    ('super_admin', 'finance.payment.import'),
    ('super_admin', 'finance.payment.export'),
    ('super_admin', 'finance.invoice.view'),
    ('super_admin', 'finance.invoice.create'),
    ('super_admin', 'finance.invoice.update'),
    ('super_admin', 'finance.invoice.delete'),
    ('super_admin', 'finance.invoice.approve'),
    ('super_admin', 'finance.invoice.export'),
    ('super_admin', 'finance.cashflow.view'),
    ('super_admin', 'finance.cashflow.export'),
    ('super_admin', 'finance.debt.view'),
    ('super_admin', 'finance.debt.adjust'),
    ('super_admin', 'operation.form.view'),
    ('super_admin', 'operation.form.manage'),
    ('super_admin', 'operation.payment-request.view'),
    ('super_admin', 'operation.payment-request.create'),
    ('super_admin', 'operation.payment-request.approve'),
    ('super_admin', 'order.export'),
    ('super_admin', 'order.status.update'),
    ('super_admin', 'order.settle'),
    ('super_admin', 'order.unlock'),
    ('super_admin', 'quote.approve'),
    ('super_admin', 'quotation.approve'),
    ('super_admin', 'data.scope.all'),

    ('accounting', 'finance.receipt.view'),
    ('accounting', 'finance.receipt.create'),
    ('accounting', 'finance.receipt.update'),
    ('accounting', 'finance.receipt.delete'),
    ('accounting', 'finance.receipt.approve'),
    ('accounting', 'finance.receipt.import'),
    ('accounting', 'finance.receipt.export'),
    ('accounting', 'finance.payment.view'),
    ('accounting', 'finance.payment.create'),
    ('accounting', 'finance.payment.update'),
    ('accounting', 'finance.payment.delete'),
    ('accounting', 'finance.payment.approve'),
    ('accounting', 'finance.payment.import'),
    ('accounting', 'finance.payment.export'),
    ('accounting', 'finance.invoice.view'),
    ('accounting', 'finance.invoice.create'),
    ('accounting', 'finance.invoice.update'),
    ('accounting', 'finance.invoice.delete'),
    ('accounting', 'finance.invoice.approve'),
    ('accounting', 'finance.invoice.export'),
    ('accounting', 'finance.cashflow.view'),
    ('accounting', 'finance.cashflow.export'),
    ('accounting', 'finance.debt.view'),
    ('accounting', 'commission.view'),
    ('accounting', 'commission.manage'),
    ('accounting', 'commission.approve'),
    ('accounting', 'commission.export'),
    ('accounting', 'report.view'),
    ('accounting', 'report.export'),
    ('accounting', 'customer.view'),
    ('accounting', 'supplier.view'),
    ('accounting', 'order.view'),
    ('accounting', 'operation.payment-request.view'),
    ('accounting', 'operation.payment-request.approve'),
    ('accounting', 'data.scope.all'),

    ('operation', 'booking.view'),
    ('operation', 'booking.manage'),
    ('operation', 'tour.view'),
    ('operation', 'tour.manage'),
    ('operation', 'guide.view'),
    ('operation', 'guide.manage'),
    ('operation', 'supplier.view'),
    ('operation', 'supplier.manage'),
    ('operation', 'order.view'),
    ('operation', 'order.manage'),
    ('operation', 'order.export'),
    ('operation', 'quote.view'),
    ('operation', 'quotation.view'),
    ('operation', 'customer.view'),
    ('operation', 'operation.form.view'),
    ('operation', 'operation.form.manage'),
    ('operation', 'operation.payment-request.view'),
    ('operation', 'operation.payment-request.create'),
    ('operation', 'report.view'),
    ('operation', 'data.scope.branch'),

    ('sales', 'booking.view'),
    ('sales', 'booking.manage'),
    ('sales', 'tour.view'),
    ('sales', 'tour.manage'),
    ('sales', 'supplier.view'),
    ('sales', 'order.view'),
    ('sales', 'order.manage'),
    ('sales', 'order.export'),
    ('sales', 'quote.view'),
    ('sales', 'quote.manage'),
    ('sales', 'quotation.view'),
    ('sales', 'quotation.manage'),
    ('sales', 'customer.view'),
    ('sales', 'customer.manage'),
    ('sales', 'commission.view'),
    ('sales', 'report.view'),
    ('sales', 'data.scope.department')
)
INSERT INTO "RolePermission" (id, "roleId", permission, "createdAt")
SELECT md5(r.id || ':' || rp.permission), r.id, rp.permission, now()
FROM role_permissions rp
JOIN "Role" r ON r.code = rp.code
ON CONFLICT ("roleId", permission) DO NOTHING;
